"""Minimal HTTP service generated by `runway init`.

Listens on $PORT (set by Cloud Run), writes structured JSON logs to stdout
and shuts down gracefully on SIGTERM.
"""

import json
import os
import signal
import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer


def log(severity, message, **fields):
    print(json.dumps({"severity": severity, "message": message, **fields}), flush=True)


class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/healthz":
            body = b"ok"
            content_type = "text/plain"
        else:
            body = json.dumps(
                {
                    "message": os.environ.get("GREETING", "Hello from runway!"),
                    "service": os.environ.get("K_SERVICE", "local"),
                    "revision": os.environ.get("K_REVISION", "local"),
                }
            ).encode()
            content_type = "application/json"
        self.send_response(200)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, fmt, *args):
        log("INFO", fmt % args, path=self.path)


def main():
    port = int(os.environ.get("PORT", "8080"))
    server = ThreadingHTTPServer(("0.0.0.0", port), Handler)

    def shutdown(signum, _frame):
        log("INFO", "received signal, shutting down", signal=signum)
        threading.Thread(target=server.shutdown, daemon=True).start()

    signal.signal(signal.SIGTERM, shutdown)
    signal.signal(signal.SIGINT, shutdown)
    log("INFO", f"listening on port {port}", log_level=os.environ.get("LOG_LEVEL", "info"))
    server.serve_forever()


if __name__ == "__main__":
    main()
